"""Made changes to users model

Revision ID: 6c5be6a9d1fb
Revises: aadcc5bb33a5
Create Date: 2022-01-28 07:41:28.707655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5be6a9d1fb'
down_revision = 'aadcc5bb33a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
